/// <reference path="SweetSoftScript.js" />

SweetSoftScript.ResourceText = {
    "notifyTitle": 'Thông báo',
    "mainworkTitle": "Bản thiết kế chính",
    "ghinhanThongSo": "Ghi nhận thông số sản xuất",
    "btnShowRecord": "Ghi nhận thông số",
    "btnInfo": "Thông tin đối tượng",
    "btnCheckAll": "Chọn tất cả",
    "btnUnCheckAll": "Bỏ chọn tất cả",
    "btnSaveRecord": "Đồng ý",
    "btnSelect": "Chọn",
    "btnSelectAll": "Chọn tất cả",
    "btnApply": "Đồng ý",
    "btnDeleteMW": "Xóa",
    "btnRename": "Đổi tên bản thiết kế",
    "renameWindow": "Đổi tên bản thiết kế",
    "btnPlus": "Tạo loại trục mới",
    "btnRemoveSelect": "Bỏ chọn",
    "btnDetail": "Chi tiết",
    "btnAddSubwork": "Thành phần phụ",
    "rdoLineMain": "Đường chuyển chính",
    "rdoLineSub": "Đường chuyển phụ",
    "worktask": "công việc chính",
    "alertErrorSave": "Đã xảy ra lỗi trong quá trình lưu.",
    "confirmLostData": "Bản thiết kế này đã có sự thay đổi, bạn có muốn lưu không ?",
    "confirmUnsaveRenamed": "Bản thiết kế này đã đổi tên, bạn có muốn lưu không ?",
    "processChangeDeptorWork": "Chuyển công tác",
    "changeDeptorWorkDone": "Chuyển công tác thành công.",
    "confirmDeleteLine": "Khi xóa đường chuyển sẽ ảnh hưởng đến tiến trình ghi nhận và sản xuất bên trong.",
    "confirmDeleteMainWork": "Khi xóa loại trục này sẽ ảnh hưởng đến tiến trình ghi nhận và sản xuất bên trong.",
    "cannotDeleteMultiNode": "Không thể xóa nhiều công việc hoặc phòng ban!",
    "dept": "bộ phận",
    "start": "Đầu vào",
    "end": "Đầu ra",
    "subwork": "công việc phụ",
    "worktaskofSubwork": "Công việc liên quan",
    "mustEnterSubworkName": "Thành phần phụ phải có tên.<br/>Bạn có chắc chắn muốn xóa thành phần phụ này ?",
    "titleOutline": "Tổng thể",
    "edge": "Qui cách đường chuyển",
    "vertex": "Qui cách thành phần",
    "groupSubwork": "Nhóm công việc phụ",
    "groupWorktask": "Công việc chính",
    "groupDept": "Bộ phận",
    "startPlace": "Nơi bắt đầu",
    "endPlace": "Nơi kết thúc",
    "xulytheoong": "Xử lý theo ống",
    "doesnot": "Không có",
    "ComponentName": "Tên thành phần",
    "ComponentType": "Loại thành phần",
    "relatedWork": "Công việc liên quan",
    "relatedMainStep": "Bước chính liên quan",
    "listWorktask": "Danh sách công việc",
    "listDept": "Danh sách phòng ban",
    "listMainWork": "Danh sách bản thiết kế",
    "listMachinery": "Danh sách trục",
    "listGraphictype": "Danh sách loại mẫu đồ họa",
    "notHaveModifyRight": "Bạn không thể chỉnh sửa bản thiết kế vì chưa được phân quyền.",
    "resetThisDesign": "Làm lại bản thiết kế này",
    "createProductionButton": "Tạo ghi nhận sản xuất",
    "confirmResetThisDesign": "Bạn có chắc chắn sẽ làm lại bản thiết kế này ?",
    "viewOutlineDesign": "Xem tổng thể thiết kế",
    "saveThisDesign": "Lưu màn hình làm việc hiện tại",
    "backToMainWork": "Trở về màn hình chính",
    "cannotDeleteStartAndEnd": "Thành phần ở bước đầu và bước cuối không thể bị xóa.",
    "errorWhileProcess": "Đã xảy ra lỗi trong quá trình thực hiện."
}