/// <reference path="SweetSoftScript.js" />

SweetSoftScript.ResourceText = {
    "notifyTitle": 'Notice',
    "mainworkTitle": "Main workflow",
    "ghinhanThongSo": "Production parameters recognition",
    "btnShowRecord": "Recorded",
    "btnInfo": "Object information",
    "btnCheckAll": "Select all",
    "btnUnCheckAll": "Uncheck all",
    "btnSaveRecord": "Agree",
    "btnSelect": "Selected",
    "btnSelectAll": "Select all",
    "btnApply": "Agree",
    "btnDeleteMW": "Delete",
    "btnRename": "Rename workflow",
    "renameWindow": "Rename workflow",
    "btnPlus": "Create new axis",
    "btnRemoveSelect": "Uncheck",
    "btnDetail": "Detail",
    "btnAddSubwork": "Sub-components",
    "rdoLineMain": "Main chute",
    "rdoLineSub": "Sub chute",
    "worktask": "worktask",
    "alertErrorSave": "An error occurred during save.",
    "confirmLostData": "This design has been changed, you may want to save it?",
    "confirmUnsaveRenamed": "This design has been changed it's name, you may want to save it?",
    "processChangeDeptorWork": "Transfer jobs",
    "changeDeptorWorkDone": "Successfully transferred.",
    "confirmDeleteLine": "When deleting this line will affect the progress recorded and produced inside.",
    "confirmDeleteMainWork": "When deleting this workflow will affect the progress recorded and produced inside.",
    "cannotDeleteMultiNode": "Unable to delete multiple jobs or departments!",
    "dept": "department",
    "start": "Begin",
    "end": "End",
    "subwork": "Sub-working",
    "worktaskofSubwork": "Related work",
    "mustEnterSubworkName": "Sub-components must be named. <br/> Are You sure to delete this sub-components?",
    "titleOutline": "Overall",
    "edge": "Line specifications",
    "vertex": "Constituent specifications",
    "groupSubwork": "Sub-working group",
    "groupWorktask": "Main work",
    "groupDept": "Parts",
    "startPlace": "Start at",
    "endPlace": "Finish at",
    "xulytheoong": "Xử lý theo ống",
    "doesnot": "None",
    "ComponentName": "Name of components",
    "ComponentType": "Component type",
    "relatedWork": "Related work",
    "relatedMainStep": "Related main steps",
    //info window
    "listWorktask": "List of jobs",
    "listDept": "List of departments",
    "listMainWork": "List blueprints",
    "listMachinery": "List axis",
    "listGraphictype": "List of graphic types",
    "notHaveModifyRight": "You can not modify the design as yet been authorized.",
    "resetThisDesign": "Reset this design",
    "createProductionButton": "Start recording",
    "confirmResetThisDesign": "Are you sure to reset this design ?",
    "viewOutlineDesign": "View the overall design",
    "saveThisDesign": "Save current desktop",
    "backToMainWork": "Return to the main screen",
    "cannotDeleteStartAndEnd": "The composition of the begin and end step can not be deleted.",
    "errorWhileProcess": "An error occurred during execution."
}