using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
    /// <summary>
    /// Controller class for tblBacking
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblBackingController
    {
        // Preload our schema..
        TblBacking thisSchemaLoad = new TblBacking();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblBackingCollection FetchAll()
        {
            TblBackingCollection coll = new TblBackingCollection();
            Query qry = new Query(TblBacking.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBackingCollection FetchByID(object BackingID)
        {
            TblBackingCollection coll = new TblBackingCollection().Where("BackingID", BackingID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBackingCollection FetchByQuery(Query qry)
        {
            TblBackingCollection coll = new TblBackingCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object BackingID)
        {
            return (TblBacking.Delete(BackingID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object BackingID)
        {
            return (TblBacking.Destroy(BackingID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string BackingName,bool IsObsolete)
	    {
		    TblBacking item = new TblBacking();
		    
            item.BackingName = BackingName;
            
            item.IsObsolete = IsObsolete;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(short BackingID,string BackingName,bool IsObsolete)
	    {
		    TblBacking item = new TblBacking();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.BackingID = BackingID;
				
			item.BackingName = BackingName;
				
			item.IsObsolete = IsObsolete;
				
	        item.Save(UserName);
	    }
    }
}
