using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
    /// <summary>
    /// Controller class for tblCustomerQuotationDetail
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblCustomerQuotationDetailController
    {
        // Preload our schema..
        TblCustomerQuotationDetail thisSchemaLoad = new TblCustomerQuotationDetail();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblCustomerQuotationDetailCollection FetchAll()
        {
            TblCustomerQuotationDetailCollection coll = new TblCustomerQuotationDetailCollection();
            Query qry = new Query(TblCustomerQuotationDetail.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCustomerQuotationDetailCollection FetchByID(object Id)
        {
            TblCustomerQuotationDetailCollection coll = new TblCustomerQuotationDetailCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCustomerQuotationDetailCollection FetchByQuery(Query qry)
        {
            TblCustomerQuotationDetailCollection coll = new TblCustomerQuotationDetailCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblCustomerQuotationDetail.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblCustomerQuotationDetail.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int CustomerId,int ProductTypeID,int ProcessTypeID,short CurrencyID,string PricingName,string GLCode,string Description,decimal OldSteelBase,decimal NewSteelBase,string UnitOfMeasure)
	    {
		    TblCustomerQuotationDetail item = new TblCustomerQuotationDetail();
		    
            item.CustomerId = CustomerId;
            
            item.ProductTypeID = ProductTypeID;
            
            item.ProcessTypeID = ProcessTypeID;
            
            item.CurrencyID = CurrencyID;
            
            item.PricingName = PricingName;
            
            item.GLCode = GLCode;
            
            item.Description = Description;
            
            item.OldSteelBase = OldSteelBase;
            
            item.NewSteelBase = NewSteelBase;
            
            item.UnitOfMeasure = UnitOfMeasure;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int CustomerId,int ProductTypeID,int ProcessTypeID,short CurrencyID,string PricingName,string GLCode,string Description,decimal OldSteelBase,decimal NewSteelBase,string UnitOfMeasure)
	    {
		    TblCustomerQuotationDetail item = new TblCustomerQuotationDetail();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CustomerId = CustomerId;
				
			item.ProductTypeID = ProductTypeID;
				
			item.ProcessTypeID = ProcessTypeID;
				
			item.CurrencyID = CurrencyID;
				
			item.PricingName = PricingName;
				
			item.GLCode = GLCode;
				
			item.Description = Description;
				
			item.OldSteelBase = OldSteelBase;
				
			item.NewSteelBase = NewSteelBase;
				
			item.UnitOfMeasure = UnitOfMeasure;
				
	        item.Save(UserName);
	    }
    }
}
