using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
    /// <summary>
    /// Controller class for tblProgress
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblProgressController
    {
        // Preload our schema..
        TblProgress thisSchemaLoad = new TblProgress();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblProgressCollection FetchAll()
        {
            TblProgressCollection coll = new TblProgressCollection();
            Query qry = new Query(TblProgress.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblProgressCollection FetchByID(object JobID)
        {
            TblProgressCollection coll = new TblProgressCollection().Where("JobID", JobID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblProgressCollection FetchByQuery(Query qry)
        {
            TblProgressCollection coll = new TblProgressCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object JobID)
        {
            return (TblProgress.Delete(JobID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object JobID)
        {
            return (TblProgress.Destroy(JobID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int JobID,DateTime? ProofDate,DateTime? ReproDate,short? ReproStatusID,DateTime? CylinderDate,short? CylinderStatusID,DateTime? DeliveryDate,DateTime? EngravingDate,DateTime? DeReDate,string Note,string CreatedBy,DateTime? CreatedOn,string ModifiedBy,DateTime? ModifiedOn)
	    {
		    TblProgress item = new TblProgress();
		    
            item.JobID = JobID;
            
            item.ProofDate = ProofDate;
            
            item.ReproDate = ReproDate;
            
            item.ReproStatusID = ReproStatusID;
            
            item.CylinderDate = CylinderDate;
            
            item.CylinderStatusID = CylinderStatusID;
            
            item.DeliveryDate = DeliveryDate;
            
            item.EngravingDate = EngravingDate;
            
            item.DeReDate = DeReDate;
            
            item.Note = Note;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int JobID,DateTime? ProofDate,DateTime? ReproDate,short? ReproStatusID,DateTime? CylinderDate,short? CylinderStatusID,DateTime? DeliveryDate,DateTime? EngravingDate,DateTime? DeReDate,string Note,string CreatedBy,DateTime? CreatedOn,string ModifiedBy,DateTime? ModifiedOn)
	    {
		    TblProgress item = new TblProgress();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.JobID = JobID;
				
			item.ProofDate = ProofDate;
				
			item.ReproDate = ReproDate;
				
			item.ReproStatusID = ReproStatusID;
				
			item.CylinderDate = CylinderDate;
				
			item.CylinderStatusID = CylinderStatusID;
				
			item.DeliveryDate = DeliveryDate;
				
			item.EngravingDate = EngravingDate;
				
			item.DeReDate = DeReDate;
				
			item.Note = Note;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
	        item.Save(UserName);
	    }
    }
}
