using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
    /// <summary>
    /// Controller class for tblRolePermission
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblRolePermissionController
    {
        // Preload our schema..
        TblRolePermission thisSchemaLoad = new TblRolePermission();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblRolePermissionCollection FetchAll()
        {
            TblRolePermissionCollection coll = new TblRolePermissionCollection();
            Query qry = new Query(TblRolePermission.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblRolePermissionCollection FetchByID(object RoleID)
        {
            TblRolePermissionCollection coll = new TblRolePermissionCollection().Where("RoleID", RoleID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblRolePermissionCollection FetchByQuery(Query qry)
        {
            TblRolePermissionCollection coll = new TblRolePermissionCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object RoleID)
        {
            return (TblRolePermission.Delete(RoleID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object RoleID)
        {
            return (TblRolePermission.Destroy(RoleID) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(int RoleID,string FunctionID)
        {
            Query qry = new Query(TblRolePermission.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("RoleID", RoleID).AND("FunctionID", FunctionID);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int RoleID,string FunctionID,bool AllowAdd,bool AllowEdit,bool AllowDelete,bool AllowUpdateStatus,bool AllowOther,bool AllowLockUnlock)
	    {
		    TblRolePermission item = new TblRolePermission();
		    
            item.RoleID = RoleID;
            
            item.FunctionID = FunctionID;
            
            item.AllowAdd = AllowAdd;
            
            item.AllowEdit = AllowEdit;
            
            item.AllowDelete = AllowDelete;
            
            item.AllowUpdateStatus = AllowUpdateStatus;
            
            item.AllowOther = AllowOther;
            
            item.AllowLockUnlock = AllowLockUnlock;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int RoleID,string FunctionID,bool AllowAdd,bool AllowEdit,bool AllowDelete,bool AllowUpdateStatus,bool AllowOther,bool AllowLockUnlock)
	    {
		    TblRolePermission item = new TblRolePermission();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.RoleID = RoleID;
				
			item.FunctionID = FunctionID;
				
			item.AllowAdd = AllowAdd;
				
			item.AllowEdit = AllowEdit;
				
			item.AllowDelete = AllowDelete;
				
			item.AllowUpdateStatus = AllowUpdateStatus;
				
			item.AllowOther = AllowOther;
				
			item.AllowLockUnlock = AllowLockUnlock;
				
	        item.Save(UserName);
	    }
    }
}
