using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
    /// <summary>
    /// Controller class for tblWorkFlow
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblWorkFlowController
    {
        // Preload our schema..
        TblWorkFlow thisSchemaLoad = new TblWorkFlow();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblWorkFlowCollection FetchAll()
        {
            TblWorkFlowCollection coll = new TblWorkFlowCollection();
            Query qry = new Query(TblWorkFlow.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblWorkFlowCollection FetchByID(object Id)
        {
            TblWorkFlowCollection coll = new TblWorkFlowCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblWorkFlowCollection FetchByQuery(Query qry)
        {
            TblWorkFlowCollection coll = new TblWorkFlowCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblWorkFlow.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblWorkFlow.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? FID,string Code,bool? IsFirstPage,bool? IsShow,string ContentXML,int? AxisTypeID,int MachineryProduceTypeID,string CreatedBy,DateTime? CreatedOn,string ModifiedBy,DateTime? ModifiedOn,int? IdParent)
	    {
		    TblWorkFlow item = new TblWorkFlow();
		    
            item.FID = FID;
            
            item.Code = Code;
            
            item.IsFirstPage = IsFirstPage;
            
            item.IsShow = IsShow;
            
            item.ContentXML = ContentXML;
            
            item.AxisTypeID = AxisTypeID;
            
            item.MachineryProduceTypeID = MachineryProduceTypeID;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
            item.IdParent = IdParent;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? FID,string Code,bool? IsFirstPage,bool? IsShow,string ContentXML,int? AxisTypeID,int MachineryProduceTypeID,string CreatedBy,DateTime? CreatedOn,string ModifiedBy,DateTime? ModifiedOn,int? IdParent)
	    {
		    TblWorkFlow item = new TblWorkFlow();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.FID = FID;
				
			item.Code = Code;
				
			item.IsFirstPage = IsFirstPage;
				
			item.IsShow = IsShow;
				
			item.ContentXML = ContentXML;
				
			item.AxisTypeID = AxisTypeID;
				
			item.MachineryProduceTypeID = MachineryProduceTypeID;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
			item.IdParent = IdParent;
				
	        item.Save(UserName);
	    }
    }
}
