using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
    /// <summary>
    /// Controller class for tblEngravingEtching
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblEngravingEtchingController
    {
        // Preload our schema..
        TblEngravingEtching thisSchemaLoad = new TblEngravingEtching();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblEngravingEtchingCollection FetchAll()
        {
            TblEngravingEtchingCollection coll = new TblEngravingEtchingCollection();
            Query qry = new Query(TblEngravingEtching.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblEngravingEtchingCollection FetchByID(object EngravingID)
        {
            TblEngravingEtchingCollection coll = new TblEngravingEtchingCollection().Where("EngravingID", EngravingID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblEngravingEtchingCollection FetchByQuery(Query qry)
        {
            TblEngravingEtchingCollection coll = new TblEngravingEtchingCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object EngravingID)
        {
            return (TblEngravingEtching.Delete(EngravingID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object EngravingID)
        {
            return (TblEngravingEtching.Destroy(EngravingID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int CylinderID,int Sequence,int JobID,string ScreenLpi,string CellType,int? Stylus,string Screen,double? Angle,string Gamma,double? TargetCellSize,double? TargetCellWall,double? TargetCellDepth,int? DevelopingTime,int? EtchingTime,double? ChromeCellSize,double? ChromeCellWall,double? ChromeCellDepth,byte IsCopy,string Color)
	    {
		    TblEngravingEtching item = new TblEngravingEtching();
		    
            item.CylinderID = CylinderID;
            
            item.Sequence = Sequence;
            
            item.JobID = JobID;
            
            item.ScreenLpi = ScreenLpi;
            
            item.CellType = CellType;
            
            item.Stylus = Stylus;
            
            item.Screen = Screen;
            
            item.Angle = Angle;
            
            item.Gamma = Gamma;
            
            item.TargetCellSize = TargetCellSize;
            
            item.TargetCellWall = TargetCellWall;
            
            item.TargetCellDepth = TargetCellDepth;
            
            item.DevelopingTime = DevelopingTime;
            
            item.EtchingTime = EtchingTime;
            
            item.ChromeCellSize = ChromeCellSize;
            
            item.ChromeCellWall = ChromeCellWall;
            
            item.ChromeCellDepth = ChromeCellDepth;
            
            item.IsCopy = IsCopy;
            
            item.Color = Color;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int EngravingID,int CylinderID,int Sequence,int JobID,string ScreenLpi,string CellType,int? Stylus,string Screen,double? Angle,string Gamma,double? TargetCellSize,double? TargetCellWall,double? TargetCellDepth,int? DevelopingTime,int? EtchingTime,double? ChromeCellSize,double? ChromeCellWall,double? ChromeCellDepth,byte IsCopy,string Color)
	    {
		    TblEngravingEtching item = new TblEngravingEtching();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.EngravingID = EngravingID;
				
			item.CylinderID = CylinderID;
				
			item.Sequence = Sequence;
				
			item.JobID = JobID;
				
			item.ScreenLpi = ScreenLpi;
				
			item.CellType = CellType;
				
			item.Stylus = Stylus;
				
			item.Screen = Screen;
				
			item.Angle = Angle;
				
			item.Gamma = Gamma;
				
			item.TargetCellSize = TargetCellSize;
				
			item.TargetCellWall = TargetCellWall;
				
			item.TargetCellDepth = TargetCellDepth;
				
			item.DevelopingTime = DevelopingTime;
				
			item.EtchingTime = EtchingTime;
				
			item.ChromeCellSize = ChromeCellSize;
				
			item.ChromeCellWall = ChromeCellWall;
				
			item.ChromeCellDepth = ChromeCellDepth;
				
			item.IsCopy = IsCopy;
				
			item.Color = Color;
				
	        item.Save(UserName);
	    }
    }
}
