using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblProgressReproStatus class.
	/// </summary>
    [Serializable]
	public partial class TblProgressReproStatusCollection : ActiveList<TblProgressReproStatus, TblProgressReproStatusCollection>
	{	   
		public TblProgressReproStatusCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblProgressReproStatusCollection</returns>
		public TblProgressReproStatusCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblProgressReproStatus o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the tblProgressReproStatus table.
	/// </summary>
	[Serializable]
	public partial class TblProgressReproStatus : ActiveRecord<TblProgressReproStatus>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblProgressReproStatus()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblProgressReproStatus(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblProgressReproStatus(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblProgressReproStatus(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("tblProgressReproStatus", TableType.Table, DataService.GetInstance("DataAcessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarReproStatusID = new TableSchema.TableColumn(schema);
				colvarReproStatusID.ColumnName = "ReproStatusID";
				colvarReproStatusID.DataType = DbType.Int16;
				colvarReproStatusID.MaxLength = 0;
				colvarReproStatusID.AutoIncrement = true;
				colvarReproStatusID.IsNullable = false;
				colvarReproStatusID.IsPrimaryKey = true;
				colvarReproStatusID.IsForeignKey = false;
				colvarReproStatusID.IsReadOnly = false;
				colvarReproStatusID.DefaultSetting = @"";
				colvarReproStatusID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarReproStatusID);
				
				TableSchema.TableColumn colvarReproStatusName = new TableSchema.TableColumn(schema);
				colvarReproStatusName.ColumnName = "ReproStatusName";
				colvarReproStatusName.DataType = DbType.String;
				colvarReproStatusName.MaxLength = 100;
				colvarReproStatusName.AutoIncrement = false;
				colvarReproStatusName.IsNullable = false;
				colvarReproStatusName.IsPrimaryKey = false;
				colvarReproStatusName.IsForeignKey = false;
				colvarReproStatusName.IsReadOnly = false;
				colvarReproStatusName.DefaultSetting = @"";
				colvarReproStatusName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarReproStatusName);
				
				TableSchema.TableColumn colvarDescription = new TableSchema.TableColumn(schema);
				colvarDescription.ColumnName = "Description";
				colvarDescription.DataType = DbType.String;
				colvarDescription.MaxLength = 200;
				colvarDescription.AutoIncrement = false;
				colvarDescription.IsNullable = true;
				colvarDescription.IsPrimaryKey = false;
				colvarDescription.IsForeignKey = false;
				colvarDescription.IsReadOnly = false;
				colvarDescription.DefaultSetting = @"";
				colvarDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDescription);
				
				TableSchema.TableColumn colvarGoBackToRepro = new TableSchema.TableColumn(schema);
				colvarGoBackToRepro.ColumnName = "GoBackToRepro";
				colvarGoBackToRepro.DataType = DbType.Boolean;
				colvarGoBackToRepro.MaxLength = 0;
				colvarGoBackToRepro.AutoIncrement = false;
				colvarGoBackToRepro.IsNullable = true;
				colvarGoBackToRepro.IsPrimaryKey = false;
				colvarGoBackToRepro.IsForeignKey = false;
				colvarGoBackToRepro.IsReadOnly = false;
				
						colvarGoBackToRepro.DefaultSetting = @"((0))";
				colvarGoBackToRepro.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGoBackToRepro);
				
				TableSchema.TableColumn colvarIsObsolete = new TableSchema.TableColumn(schema);
				colvarIsObsolete.ColumnName = "IsObsolete";
				colvarIsObsolete.DataType = DbType.Boolean;
				colvarIsObsolete.MaxLength = 0;
				colvarIsObsolete.AutoIncrement = false;
				colvarIsObsolete.IsNullable = false;
				colvarIsObsolete.IsPrimaryKey = false;
				colvarIsObsolete.IsForeignKey = false;
				colvarIsObsolete.IsReadOnly = false;
				colvarIsObsolete.DefaultSetting = @"";
				colvarIsObsolete.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsObsolete);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAcessProvider"].AddSchema("tblProgressReproStatus",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ReproStatusID")]
		[Bindable(true)]
		public short ReproStatusID 
		{
			get { return GetColumnValue<short>(Columns.ReproStatusID); }
			set { SetColumnValue(Columns.ReproStatusID, value); }
		}
		  
		[XmlAttribute("ReproStatusName")]
		[Bindable(true)]
		public string ReproStatusName 
		{
			get { return GetColumnValue<string>(Columns.ReproStatusName); }
			set { SetColumnValue(Columns.ReproStatusName, value); }
		}
		  
		[XmlAttribute("Description")]
		[Bindable(true)]
		public string Description 
		{
			get { return GetColumnValue<string>(Columns.Description); }
			set { SetColumnValue(Columns.Description, value); }
		}
		  
		[XmlAttribute("GoBackToRepro")]
		[Bindable(true)]
		public bool? GoBackToRepro 
		{
			get { return GetColumnValue<bool?>(Columns.GoBackToRepro); }
			set { SetColumnValue(Columns.GoBackToRepro, value); }
		}
		  
		[XmlAttribute("IsObsolete")]
		[Bindable(true)]
		public bool IsObsolete 
		{
			get { return GetColumnValue<bool>(Columns.IsObsolete); }
			set { SetColumnValue(Columns.IsObsolete, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		private SweetSoft.APEM.DataAccess.TblProgressCollection colTblProgressRecords;
		public SweetSoft.APEM.DataAccess.TblProgressCollection TblProgressRecords()
		{
			if(colTblProgressRecords == null)
			{
				colTblProgressRecords = new SweetSoft.APEM.DataAccess.TblProgressCollection().Where(TblProgress.Columns.ReproStatusID, ReproStatusID).Load();
				colTblProgressRecords.ListChanged += new ListChangedEventHandler(colTblProgressRecords_ListChanged);
			}
			return colTblProgressRecords;
		}
				
		void colTblProgressRecords_ListChanged(object sender, ListChangedEventArgs e)
		{
            if (e.ListChangedType == ListChangedType.ItemAdded)
            {
		        // Set foreign key value
		        colTblProgressRecords[e.NewIndex].ReproStatusID = ReproStatusID;
            }
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varReproStatusName,string varDescription,bool? varGoBackToRepro,bool varIsObsolete)
		{
			TblProgressReproStatus item = new TblProgressReproStatus();
			
			item.ReproStatusName = varReproStatusName;
			
			item.Description = varDescription;
			
			item.GoBackToRepro = varGoBackToRepro;
			
			item.IsObsolete = varIsObsolete;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(short varReproStatusID,string varReproStatusName,string varDescription,bool? varGoBackToRepro,bool varIsObsolete)
		{
			TblProgressReproStatus item = new TblProgressReproStatus();
			
				item.ReproStatusID = varReproStatusID;
			
				item.ReproStatusName = varReproStatusName;
			
				item.Description = varDescription;
			
				item.GoBackToRepro = varGoBackToRepro;
			
				item.IsObsolete = varIsObsolete;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ReproStatusIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ReproStatusNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DescriptionColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn GoBackToReproColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn IsObsoleteColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ReproStatusID = @"ReproStatusID";
			 public static string ReproStatusName = @"ReproStatusName";
			 public static string Description = @"Description";
			 public static string GoBackToRepro = @"GoBackToRepro";
			 public static string IsObsolete = @"IsObsolete";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
                if (colTblProgressRecords != null)
                {
                    foreach (SweetSoft.APEM.DataAccess.TblProgress item in colTblProgressRecords)
                    {
                        if (item.ReproStatusID == null ||item.ReproStatusID != ReproStatusID)
                        {
                            item.ReproStatusID = ReproStatusID;
                        }
                    }
               }
		}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
                if (colTblProgressRecords != null)
                {
                    colTblProgressRecords.SaveAll();
               }
		}
        #endregion
	}
}
