using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.Logs.DataAccess
{
    /// <summary>
    /// Controller class for tblAllDataLogs
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblAllDataLogController
    {
        // Preload our schema..
        TblAllDataLog thisSchemaLoad = new TblAllDataLog();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblAllDataLogCollection FetchAll()
        {
            TblAllDataLogCollection coll = new TblAllDataLogCollection();
            Query qry = new Query(TblAllDataLog.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAllDataLogCollection FetchByID(object Id)
        {
            TblAllDataLogCollection coll = new TblAllDataLogCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAllDataLogCollection FetchByQuery(Query qry)
        {
            TblAllDataLogCollection coll = new TblAllDataLogCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblAllDataLog.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblAllDataLog.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public TblAllDataLog Insert(TblAllDataLog obj)
        {
            TblAllDataLog item = new TblAllDataLog();

            item.ContentLogs = obj.ContentLogs;

            item.ActionDate = obj.ActionDate;

            item.UserIP = obj.UserIP;

            item.Save(UserName);

            return item;
        }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public TblAllDataLog Update(TblAllDataLog obj)
        {
            TblAllDataLog item = new TblAllDataLog();
            item.MarkOld();
            item.IsLoaded = true;

            item.Id = obj.Id;

            item.ContentLogs = obj.ContentLogs;

            item.ActionDate = obj.ActionDate == null ? DateTime.Now : obj.ActionDate;

            item.UserIP = obj.UserIP;

            item.Save(UserName);

            return item;
        }
    }
}
