using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.APEM.DataAccess
{
    /// <summary>
    /// Controller class for tblProgressReproStatus
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblProgressReproStatusController
    {
        // Preload our schema..
        TblProgressReproStatus thisSchemaLoad = new TblProgressReproStatus();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblProgressReproStatusCollection FetchAll()
        {
            TblProgressReproStatusCollection coll = new TblProgressReproStatusCollection();
            Query qry = new Query(TblProgressReproStatus.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblProgressReproStatusCollection FetchByID(object ReproStatusID)
        {
            TblProgressReproStatusCollection coll = new TblProgressReproStatusCollection().Where("ReproStatusID", ReproStatusID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblProgressReproStatusCollection FetchByQuery(Query qry)
        {
            TblProgressReproStatusCollection coll = new TblProgressReproStatusCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ReproStatusID)
        {
            return (TblProgressReproStatus.Delete(ReproStatusID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ReproStatusID)
        {
            return (TblProgressReproStatus.Destroy(ReproStatusID) == 1);
        }



        /// <summary>
        /// Inserts a record, can be used with the Object Data Source
        /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public TblProgressReproStatus Insert(TblProgressReproStatus item)
        {
            item.Save(UserName);
            return item;
        }

        /// <summary>
        /// Updates a record, can be used with the Object Data Source
        /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public TblProgressReproStatus Update(TblProgressReproStatus item)
        {
            item.MarkOld();
            item.IsLoaded = true;
            item.Save(UserName);
            return item;
        }
    }
}
